---
- name: Install nginx
  become: yes
  apt: name=nginx state=present

- name: Firewall allow both HTTP and HTTPs
  become: yes
  ufw: rule=allow name="Nginx Full" state=enabled

- name: Ensure nginx service started
  become: yes
  service: name=nginx state=started enabled=yes